apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    # TODO: templatize
    - port: 51003
      targetPort: 51003
      protocol: TCP
      name: grpc
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
