steps:

  # 1: Make the docs
  - name: python:3.12
    entrypoint: bash
    args:
      - "-c"
      - |
        export PYTHONPATH=$(pwd)
        pip install -r storage-ms/requirements.txt
        make clean-proto-files && make generate-proto-files
        pip install -e ./proto
        pip install sphinx
        cd storage-ms
        pip install pydata-sphinx-theme
        cd docs
        make clean && make html

    id: Make Docs
        # pip install -r requirements.txt

  # 2: Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_DOCS_IMAGE_NAME'
      - .
      - '-f'
      - $_DOCS_DOCKERFILE_NAME
    dir: $_DOCS_DOCKERFILE_DIR
    id: Build

  # 3: Push the docs image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_DOCS_IMAGE_NAME'
    id: Push

  # 4: Set up Google Cloud project
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'config'
      - 'set'
      - 'project'
      - '${_GCP_PROJECT}'
    id: Set Project

  # 5: Authenticate kubectl
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_CLUSTER_NAME}'
      - '--region'
      - '${_CLUSTER_REGION}'
    id: Authenticate Kubernetes

    # 5: Run helm chart for app and deploy
  - name: 'gcr.io/$_GCP_PROJECT/helm'
    args:
      - 'upgrade'
      - '--install'
      - '${_RELEASE_NAME}'
      - './storage-ms/docs/helm'
      - '-f'
      - './storage-ms/docs/helm/values.yaml'
      - '--set'
      - 'image.repository=$_DOCS_IMAGE_NAME'
      - '--set'
      - 'image.tag=latest'
      - '--history-max'
      - '5'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    id: Helm Deploy

images:
  - '$_DOCS_IMAGE_NAME'

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s  # Adjust timeout as necessary

substitutions:
  _DOCS_DOCKERFILE_NAME: Dockerfile
  _DOCS_DOCKERFILE_DIR: storage-ms/docs
  _DOCS_IMAGE_NAME: gcr.io/first-hearth-447116-s1/storage-ms-docs
  _GCP_PROJECT: first-hearth-447116-s1
  _CLUSTER_NAME: skladischer-cluster-1
  _CLUSTER_REGION: europe-west3
  _RELEASE_NAME: storage-ms-docs
    #TODO: centralize configuration