# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# SOURCE: code_ms.proto
# Protobuf Python Version: 5.29.0

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'code_ms.proto'
)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcode_ms.proto\x12\x0b\x63odeservice\" \n\x0b\x43odeRequest\x12\x11\n\titem_code\x18\x01 \x01(\t\"$\n\x0c\x43odeResponse\x12\x14\n\x0cimage_base64\x18\x01 \x01(\t2P\n\x0b\x43odeService\x12\x41\n\nCreateCode\x12\x18.codeservice.CodeRequest\x1a\x19.codeservice.CodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'code_ms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODEREQUEST']._serialized_start=30
  _globals['_CODEREQUEST']._serialized_end=62
  _globals['_CODERESPONSE']._serialized_start=64
  _globals['_CODERESPONSE']._serialized_end=100
  _globals['_CODESERVICE']._serialized_start=102
  _globals['_CODESERVICE']._serialized_end=182

