# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!

import grpc
import warnings

from proto import code_ms_pb2 as code__ms__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in code_ms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CodeServiceStub(object):

    def __init__(self, channel):
        self.CreateCode = channel.unary_unary(
                '/codeservice.CodeService/CreateCode',
                request_serializer=code__ms__pb2.CodeRequest.SerializeToString,
                response_deserializer=code__ms__pb2.CodeResponse.FromString,
                _registered_method=True)


class CodeServiceServicer(object):
    def CreateCode(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCode': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCode,
                    request_deserializer=code__ms__pb2.CodeRequest.FromString,
                    response_serializer=code__ms__pb2.CodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codeservice.CodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codeservice.CodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodeService(object):
    @staticmethod
    def CreateCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codeservice.CodeService/CreateCode',
            code__ms__pb2.CodeRequest.SerializeToString,
            code__ms__pb2.CodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
