apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 50051       # Port exposed to other services
      targetPort: 50051 # Port on the container
      name: grpc
