name: Run Tests

on:
  pull_request:
  merge_group:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    name: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code.
        uses: actions/checkout@v3

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies from text file.
        run: |
          pip install -r storage-ms/requirements.txt
          pip install -r codes-ms/requirements.txt
          pip install pytest

      - name: Install Proto Module
        run: |
          pip install -e ./proto
          echo "PYTHONPATH=$(pwd)">>$GITHUB_ENV

      - name: Run Tests for Storage MS.
        env:
           DATABASE_URL: ${{ secrets.DATABASE_URL }}
           DATABASE_NAME: ${{ vars.DATABASE_NAME }}
           COLLECTION: ${{ vars.COLLECTION }}
        run: |
            pytest storage-ms/tests

      - name: Run Tests for Code Generator MS.
        env:
           RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
           RAPIDAPI_URL: ${{ vars.RAPIDAPI_URL }}
           RAPIDAPI_HOST: ${{ vars.RAPIDAPI_HOST }}
        run: |
            pytest codes-ms/tests
      
